select FirstName from student where m1>100 and m2>90;
desc student;
select * from student;
select * from student where m1>100 and m2>90;
use db2;
select * from student where m1=100 and m2=100;
select * from student where m1 between 90 and 100;
select * from student where m3 between 80 and 100;
select * from student;
select distinct m1 from student;
use db2;
create table stuinfo(Age INT,Address VARCHAR(20));
drop table stuinfo;
insert into stu_info values(20,"thevaiyur"),(16,"thevaiyur"),(21,"saudi"),(29,"france");
select * from stu_info;
select distinct Address from stu_info;
select count(*) from student;
select * from student;
select count(*) from stu_info;
select * from stu_info;
create table town(id INT, town_name VARCHAR(20), town_code INT,population INT);
insert into town values(1,"valikandapuram",621212,7000),(2,"thevaiyur",621117,350),(3,"senjeri",621216,8000),(4,"loa angeles",7121,100000);
select * from town;
select town_code,population from town where id % 3=0;